coverage:
  if: true
codeToTestRatio:
  code:
    - "**/*.go"
    - "!**/*_test.go"
    - "!**/mock_*.go"
    - "!**/mock*/*.go"
  test:
    - "**/*_test.go"
testExecutionTime:
  if: true
timeout: 3 min
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
summary:
  if: true
body:
  if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
